---
- name: "Checking git repository records are defined"
  ansible.builtin.assert:
    that:
      - iac_git_repos is defined
    fail_msg: "iac_git_repos must be defined"

- name: "Checking git repository record"
  ansible.builtin.assert:
    that:
      - iac_git_repo_record.repo is defined
      - iac_git_repo_record.dest is defined
    fail_msg: "Git repository record is missing required fields"
  loop: "{{ iac_git_repos | default([]) }}"
  loop_control:
    loop_var: iac_git_repo_record
    label: "{{ iac_git_repo_record.dest | default(iac_git_repo_record.repo | default('unknown')) }}"

- name: "Ensuring git repositories are present"
  become: "{{ (iac_git_become_user is defined) | bool }}"
  become_user: "{{ iac_git_become_user | default(omit) }}"
  ansible.builtin.git:
    repo: "{{ iac_git_repo_record.repo }}"
    dest: "{{ iac_git_repo_record.dest }}"
    version: "{{ iac_git_repo_record['version'] | default(omit) }}"
    update: "{{ iac_git_repo_record['update'] | default(omit) }}"
    force: "{{ iac_git_repo_record['force'] | default(omit) }}"
    recursive: "{{ iac_git_repo_record['recursive'] | default(omit) }}"
    single_branch: "{{ iac_git_repo_record['single_branch'] | default(omit) }}"
    remote: "{{ iac_git_repo_record['remote'] | default(omit) }}"
    accept_hostkey: "{{ iac_git_repo_record['accept_hostkey'] | default(omit) }}"
    key_file: "{{ iac_git_repo_record['key_file'] | default(omit) }}"
    depth: "{{ iac_git_repo_record['depth'] | default(omit) }}"
    refspec: "{{ iac_git_repo_record['refspec'] | default(omit) }}"
  loop: "{{ iac_git_repos | default([]) }}"
  when: (iac_git_repos | default([])) | length > 0
  loop_control:
    loop_var: iac_git_repo_record
    label: "{{ iac_git_repo_record.dest }}"
